# Generated by Django 4.1 on 2022-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conf_num', models.CharField(max_length=15, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
