# Generated by Django 4.1.1 on 2023-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_blog_image_blogpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="intro",
            field=models.TextField(
                default="this is an introduction to my blog",
                help_text="Text to describe the page",
            ),
            preserve_default=False,
        ),
    ]
